-- MySQL Script generated by MySQL Workbench
-- Sun Mar 20 21:27:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cs_webdev_final
-- -----------------------------------------------------

-- ----------------------------idPRIMARY-------------------------
-- Schema cs_webdev_final
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cs_webdev_final` ;
USE `cs_webdev_final` ;

-- -----------------------------------------------------
-- Table `cs_webdev_final`.`blog_posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cs_webdev_final`.`blog_posts` ;

CREATE TABLE IF NOT EXISTS `cs_webdev_final`.`blog_posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `blog_title` VARCHAR(255) NULL,
  `blog_body` VARCHAR(999) NULL,
  `date_posted` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS poster;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'poster' IDENTIFIED BY 'password123';

GRANT SELECT ON TABLE `mydb`.* TO 'poster';
GRANT SELECT ON TABLE `cs_webdev_final`.* TO 'poster';
GRANT SELECT, INSERT, TRIGGER ON TABLE `mydb`.* TO 'poster';
GRANT SELECT, INSERT, TRIGGER ON TABLE `cs_webdev_final`.* TO 'poster';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `mydb`.* TO 'poster';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `cs_webdev_final`.* TO 'poster';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
